DROP TABLE IF EXISTS ORDER_ITEMS CASCADE;
DROP TABLE IF EXISTS ORDERS CASCADE;
DROP TABLE IF EXISTS CUSTOMERS CASCADE;
DROP TABLE IF EXISTS ITEMS CASCADE;
DROP TABLE IF EXISTS ITEM_TYPES CASCADE;
DROP TABLE IF EXISTS BUSINESSES CASCADE;
DROP TABLE IF EXISTS SESSIONS CASCADE;