

name: Build and Deploy Ktor App to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: production
    env:
      POSTGRES_DATABASE: ${{ secrets.POSTGRES_DATABASE }}
      POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
      POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
      POSTGRES_USERNAME: ${{ secrets.POSTGRES_USERNAME }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
      KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      PRIVATE_KEY_PASSWORD: ${{ secrets.PRIVATE_KEY_PASSWORD }}
      AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
      AUTH0_AUDIENCE: ${{ secrets.AUTH0_AUDIENCE }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      DOCKER_PROJECT : ${{ vars.DOCKER_PROJECT }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Build Docker image with Ktor plugin
        run: ./gradlew publishImageToLocalRegistry

      - name: Properly Tag Docker image
        run: docker images
             docker tag ${{vars.DOCKER_PROJECT}}:latest ${{vars.REGISTRY_NAME}}.azurecr.io/${{vars.DOCKER_PROJECT}}:latest


      - name: Push Docker image to ACR
        run: docker push ${{vars.REGISTRY_NAME}}.azurecr.io/${{vars.DOCKER_PROJECT}}:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Azure WebApp Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure WebApp Deploy
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{vars.APP_NAME}}
          images: ${{vars.REGISTRY_NAME}}.azurecr.io/klejdis-business-analytics-service:latest
